### ISSUE TITLE
duplicated mapping key "type" by rendering Map of Arrays

### ISSUE THREAD

**Issue by selimok** [stoicflame/enunciate-openapi#37]
Hi,

I just discovered a openapi rendering problem. When I started swagger ui I saw "duplicated mapping key" error.

I have this property in one of my classes:

```
LinkedHashMap<String, LinkedHashSet<String>> tags;
```

This will be rendered by openapi plugin as:

```
"tags":
  description: "The list of tags and its values"
  type: object
  additionalProperties:
    type: string
  type: array
  items:
    type: string
```

While the swagger plugin generates this:

```
"tags"
  readOnly: false
  description: "The list of tags and its values"
  type: "object"
  additionalProperties:
    type: "array"
    items:
      type: "string"
```

I think the problem lies somewhere at Line 71 of DataTypeReferenceRenderer: https://github.com/stoicflame/enunciate-openapi/blame/6ffbce9cbced9dcd64b0b3d04f03d9d030e4e64f/src/main/java/dk/jyskebank/tools/enunciate/modules/openapi/DataTypeReferenceRenderer.java#L71 

The "containers" has the value  {map, array}. The implementation tries to render both as siblings instead of parent-child.  

I don't know whether this behaviour is correct in other use cases but in my case it is incorrect.

Thanks. 

Kind Regards
Selim
